### ISSUE TITLE
Can't run app without Visual Studio

### ISSUE THREAD

**Issue by sigseg5** [julianperrott/FishingFun#29]
Hi, I can't run app without VS connection. When I open the app, nothing happens.
This is logs from Event Viewer:
* Source: Application Error
```
Faulting application name: Chrome.exe, version: 1.0.0.0, time stamp: 0x8ed72337
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xe6477cce
Exception code: 0xe0434352
Fault offset: 0x0012a892
Faulting process id: 0x37f4
Faulting application start time: 0x01d6e67a5f08a498
Faulting application path: C:\Users\user\Documents\FishingFun\Source\FishingFunUI\obj\Debug\Chrome.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Faulting package full name: 
Faulting package-relative application ID:
```
* Source: .NET Runtime
```
Application: Chrome.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at FishingFun.App..ctor()
   at FishingFun.App.Main()
```
Do you have any ideas how to fix this?

**Comment by Qylie** [comment]
I have so many errors!  I don't know what I did wrong :-( 
[https://content.screencast.com/users/TheSpark/folders/Snagit/media/78a4cb65-fbdd-4623-80c5-7f4b64d57f5a/07.05.2021-09.55.png](url)
